<template>
    <div class="d-flex flex-column">
        <div class="d-flex align-items-end p-5 img-header">
            <h1 class="mb-4 text-white">Privacy Policy</h1>
        </div>
        <div class="d-flex justify-content-center flex-fill">
            <div class="align-self-center py-5">
                <div class="mx-auto w-75">
                    <h3 class="my-4">Introduction</h3>
                    <p>We take your privacy seriously and are committed to safeguarding your personal information at Emaar Hospitality Group LLC (which term includes all subsidiaries of Emaar Hospitality Group LLC). (“Company”, “we” or “us” or “Emaar”) values you as our guest, respect your privacy and are committed to protecting it through our compliance with this policy.</p>
                    <p>This policy describes the sources of your personal data that we may collect from you or that you may provide to us and our practices for collecting, using, maintaining, protecting and disclosing that information.</p>
                    <p>Please read this policy carefully to understand our policies and practices regarding your information and how we will treat it. If you do not agree with our policies and practices, your choice is not to use our platforms. By accessing or using our platforms, you agree to this privacy policy.</p>
                    <p>If you have any questions or concerns about this privacy policy or your personal information, please contact us using the details provided in Section – ‘How do you contact us?’.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">What are the information we collect from you?</h3>
                    <p>Personal information you give us</p>
                    <p>The information we collect on or through our platforms may include:</p>
                    <ul><li>Information that you provide by filling in forms. This may include information provided at the time of registering to use our Website, subscribing to our service, registering for newsletter, using the ‘contact us’ form, using the “Enquiry” forms, using the ‘WeCare’ form, using the careers portal or requesting further services, entering a contest or promotion sponsored by us, reporting a problem with our Website. The personal information that you provide us with may include your name, email address, phone number, nationality, residential address, identification proof (such as Emirates ID, or Passport), credit card details, partner issued membership ID etc</li><li>Records and copies of your correspondence (including e-mail addresses), when you contact us.</li><li>Information that you provide to surveys that trigger for feedback to help us improve ourselves, details of transactions you carry out through our Website and of the fulfilment of your orders. You may be required to provide financial information before placing an order or making payment through our Website.</li></ul>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Other Information we collect</h3>
                    <p>There is other information we may collect that does not directly reveal your specific identity or does not directly relate to you as an individual. We may automatically collect the following information when you use our service:</p>
                    <ul><li>Your equipment, browsing actions and patterns collected automatically as you navigate through our websites.</li><li>Usage details, time of requests, Browser types, operating system, IP addresses and information collected through cookies, web beacons and other tracking technologies.</li><li>Details of your visits to our Website, including traffic data, location data, logs and other communication data and the resources that you access and use on the Website.</li></ul>
                    <p>The information we collect automatically is statistical data. It helps us to improve our Website and to deliver a better and more personalized service by enabling us to:</p>
                    <ul><li>Estimate our audience size and usage patterns.</li><li>Store information about your preferences, allowing us to customize our Website according to your individual interests.</li><li>Speed up your searches.</li><li>Recognize you when you return to our Website.</li></ul>
                    <p>The technologies we use for this automatic data collection may include:</p>
                    <ul><li><strong>Cookies:&nbsp;</strong>A cookie is a small piece of data, which includes an identifier made of letters and numbers that is sent by a web browser and stored on your computer. Cookies are used as a reliable mechanism to remember information about you, so your interaction with our website is seamlessly simple. Cookies typically do not contain any information that personally identify you, but personal information that we store about you may be linked to the information stored in and obtained from cookies. Please&nbsp;<a href="https://www.emaarhospitality.com/en/gdpr/cookiepolicy/" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Links', 'eventAct':'Click', 'eventLbl': 'emaarhospitality.com/en/gdpr/cookiepolicy/', 'eventVal': 0, 'nonInteraction': 0});">CLICK HERE</a>&nbsp;for details on Cookie Policy.</li><li><strong>Flash Cookies:&nbsp;</strong>Certain features of our Website may use local stored objects (or Flash cookies) to collect and store information about your preferences and navigation to, from and on our Website. Flash cookies are not managed by the same browser settings as are used for browser cookies.</li><li><strong>Web Beacons:&nbsp;</strong>Pages of the Website and our e-mails may contain small electronic files known as web beacons (also referred to as clear gifs. pixel tags and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an e-mail and for other related website statistics (for example, recording the popularity of certain website content and verifying system and server integrity).</li></ul>
                    <p>We use cookies for the following purposes:</p>
                    <ul><li>To identify you when you visit our platforms and to help you navigate through our platforms;</li><li>To help determine if you are logged into our platforms:</li><li>To store information about your preferences and to personalize our platforms for you;</li><li>To secure and protect your user account and our platforms; and</li><li>To analyse the use and performance of our platforms.</li></ul>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Information we receive form others</h3>
                    <p>We work closely with third parties and receive information about you from them as well. We also collect personal information from individuals who may refer you as a friend to our loyalty schemes or products or services. We ask these individuals to confirm that you are happy to hear from us.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">What are the sources of your Personal Data?</h3>
                    <p>The sources of your personal data collected (collectively referred as “Platforms” in this policy) may include without limitation the following</p>
                    <ul><li><strong>Emaar websites</strong>These are websites we created for you that are operated by us, they include websites operated by Emaar under our own domains and web addresses (URLs) and our own micro-sites that are part of a third-party social media networks such as Facebook, Twitter, or Instagram.</li><li><strong>Emails, text messaging services, and other electronic messages:&nbsp;</strong>These are the electronic text-based interaction between you and Emaar.</li><li><strong>Emaar mobile applications:</strong>These are smartphone applications created for you and operated by Emaar or one of our partners.</li><li><strong>Emaar Customer Service:</strong>Any communication between you and our Customer Service center (e.g. phone, chatbot, email, etc.).</li><li><strong>Offline registration forms:&nbsp;</strong>These include printed registrations, surveys, or questionnaires Emaar collects via registration forms, contests, events, and various promotions.</li><li><strong>Advertising:</strong>You might interact with one of our or our partners’ advertisements on our websites and apps and we might receive and collect this information.</li><li><strong>Career Portal:&nbsp;</strong>These includes recruitment portal across Emaar.</li><li><strong>Data we create:&nbsp;</strong>Emaar may also create data about you, such as your reservation history.</li><li><strong>Data from other sources:&nbsp;</strong>These include social media networks, market research agencies, Emaar promotional partners, public sources, and data received when we acquire other companies.</li><li><strong>Third Party Partners:&nbsp;</strong>Online booking web sites or agents.</li></ul>
                    <p>This policy does not apply to information collected:</p>
                    <ul><li>through any other means, including any other website operated by any third party; or</li><li>by any third party, including through any application or content (including advertising) that may link to the Website.</li></ul>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Whay do we collect and how do we use your Personal Information?</h3>
                    <p>We use personal information for several legitimate interests, including to provide and improve our services, administer our relationship with you and our business.</p>
                    <p><strong>To facilitate any reservation or booking requests we receive from you:</strong></p>
                    <p>To facilitate a reservation or booking request we would need to collect and use the following personal information: name, email address, phone number, residential address, nationality, identification proof (such as Emirates ID or Passport) and credit card details. We would need to collect and use your personal information to fulfil our contractual obligations towards the service(s) requested by you (such as room booking, dining reservation, etc.).</p>
                    <p>In the event you have any special requests, we would need to collect additional personal information which may also include sensitive information. For example:</p>
                    <ul><li>if you require our assistance with applying for a travel visa, we would collect additional information such as photograph and passport details;</li><li>if you would like to inform us about any food allergies, we would use and retain this information to help us tailor our cuisines to your needs and to help us remember your preferences; or</li><li>if you require any special assistance such as accessible parking, wheelchair assistance, etc., we may collect and retain this personal information to facilitate your request and be more proactive in the future;</li><li>We shall only collect and use your personal information (especially sensitive information) based on your explicit consent and solely for the purposes mentioned above.</li></ul>
                    <p><strong>To manage your membership of our loyalty programs – ‘U BY EMAAR’:</strong></p>
                    <p>We encourage and invite you to join our loyalty program, so that they may benefit from exclusive offers, discounts, and promotions available to members. You may join our loyalty program by registering online on the ‘U BY EMAAR’ webpage –&nbsp;<a href="https://www.ubyemaar.com/" target="_blank" rel="noreferrer noopener" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Links', 'eventAct':'Click', 'eventLbl': 'ubyemaar.com/', 'eventVal': 0, 'nonInteraction': 0});">https://www.ubyemaar.com</a></p>
                    <p>Once you register for our loyalty program, we would collect and process the following personal information: name, telephone number, email ID, ‘U BY EMAAR’ ID and transaction history. We would need to collect and use your personal information to fulfil our contractual obligations under the loyalty program.</p>
                    <p>As part of the loyalty program, we would also send our members information regarding special offers, discounts and promotions in pursuit of legitimate business interests. In the event you prefer not to receive such information, you may opt-out by following the instruction provided Section – “How to opt-out?”.</p>
                    <p><strong>To respond to any queries made by you:</strong></p>
                    <p>We would need to collect and use the following personal information: name, email address, phone number, nationality and details of your enquiry.</p>
                    <p>In certain cases, your enquiry may relate to a specific service request, for example: requesting a copy of an invoice. For such requests, we need to use your personal information to help us respond to your request and to fulfil our contractual obligations under the requested service.</p>
                    <p>Additionally, when you call our customer service centre, we would maintain a record of the communications, including call recordings, in pursuit of our legitimate business interest to monitor and improve the quality of our guest support.</p>
                    <p><strong>To provide you with information about Emaar’s services and latest offers:</strong></p>
                    <p>It is in our legitimate business interests to send you information about Emaar’s services and latest offers. We use your personal information such as email ID and/ or contact number to share information relating to Emaar’s services and latest offers that may be of interest to you. In the event you prefer not to receive such information, you may opt-out by following the instruction provided Section – “How to opt-out?”.</p>
                    <p><strong>To personalize the information we send you:</strong></p>
                    <p>We may combine the information we receive and collect about you to better understand your interests and preferences so that we can provide you with an experience that is tailored to those interests and preferences. For example, we may do this by offering you use of certain facilities (such as dining, spa or lifestyle events) that you are most likely to be interested in, or sending you personalized offers, discounts or promotions by email (where you have agreed to receive our emails), or advertising content that is relevant to your interests. In the event you prefer not to receive such information, you may opt out by following the instruction provided Section – “How to opt out?”.</p>
                    <p><strong>To enable you to avail special offers and benefits from our business partners:</strong></p>
                    <p>We have strong and longstanding partnerships with business partners across sectors including Travel, Entertainment, and Lifestyle. Our partnerships allow you to avail special benefits and offers from our business partners. For example, Emirates Skyward members can avail Skywards Miles when they stay at our select hotels and resorts.</p>
                    <p>To help you avail of these benefits, we would need to collect and share the following personal information: name, Partner issued Membership ID and transaction history, with our business partners. We would need to collect and process your personal information to fulfil our contractual obligations towards our business partners and to ensure you avail the best of benefits and offers. To see more information about our current partnerships please visit our websites.</p>
                    <p><strong>To request your feedback, and to respond to complaints:</strong></p>
                    <p>Your satisfaction is our utmost priority and we proactively take necessary steps to ensure you are well satisfied with our services.</p>
                    <p>To help us respond to your feedback or complaints, we would need to collect the following personal information: name, email ID, transaction details (such as Emaar hotel and room type you stayed at) and your feedback/ complaints in the submission form or through a survey after a hotel stay or dining experience.</p>
                    <p>We collect and use your personal information in pursuit of our legitimate business interests to address your concerns and to take necessary steps towards continual improvement. In the event you prefer not to receive such information, you may opt out by following the instruction provided Section – “How to opt out?”.</p>
                    <p>To establish a working relationship with corporate clients:</p>
                    <p>We collect/ receive personal information about you through one of the following channels:</p>
                    <ul><li>When you participate in any of our sales, marketing and thought leadership events organized or hosted by Emaar;</li><li>When our sales executive or business leaders visit events organized by external organizations (including the company you represent);</li><li>We collect from our sales executives or business leaders who share a professional/ personal relationship with you; or</li><li>We collect from publicly available information that you have shared on professional networking platforms such as LinkedIn.</li></ul>
                    <p>We would need to collect the following personal information: name, email ID, contact number, designation, and the company you represent. We use this information for the purposes, listed below, in pursuit of our legitimate business:</p>
                    <ul><li>To share information relating to Emaar services;</li><li>To invite you to future events, that may be of interest to you and/ or the company you represent; and</li><li>To establish a working relationship with the company you represent.</li></ul>
                    <p><strong>To enter into, renew or fulfil service contracts with our corporate clients:</strong></p>
                    <p>Over the years we have established a strong working relationship with many corporate companies to facilitate group bookings, reservations, and events. To facilitate our service offerings with our corporate clients, we enter into contractual agreements that require us to collect personal information of the company representatives, such as name, email ID, designation, and the company you represent.</p>
                    <p>Further, in the event of any corporate bookings or reservations, we would also collect information of guests availing the services and benefits under our corporate agreements. The personal information collected would include name, company employee ID and passport/identification proof. We collect and use this information to help us fulfil our contractual obligations towards our corporate clients to enforce or apply our terms of use or terms of sale and other agreements, including for billing and collection purposes.</p>
                    <p><strong>To facilitate email campaigns carried out by our sales and marketing departments:</strong></p>
                    <p>As part of our email campaigns, we track whenever you receive, open, click a link, or download any attachments from an e-mail you receive from Emaar. We will carry out automated profiling of such information to evaluate your interest in our service offerings or promotions. This processing will enable us to identify and target potential guests or business partners, tailor our marketing and provide you with relevant and timely content based on your interests, in pursuit of our legitimate business interests. In the event you prefer not to receive such information, you may opt out by following the instruction provided Section – “How to opt out?”.</p>
                    <p><strong>To comply with legal requirements and exercise or defend legal claims:</strong></p>
                    <p>We may need to process and retain your personal information to comply with legal requirements to which we are subject (for example in relation to health and safety). It is in our legitimate interests to process personal information for the purposes of exercising and defending legal claims. Processing personal information may also be necessary to ensure compliance with the relevant legal and regulatory obligations.</p>
                    <p><strong>To process your payments and protect against fraudulent transactions:</strong></p>
                    <p>We may need to process your personal information to keep your payments safe and secure and protect against fraudulent transactions. It is in our legitimate interests to process personal information to keep your payments secure and to prevent fraud. Processing personal information in this way may also be necessary to ensure compliance with the relevant legal and regulatory obligations.</p>
                    <p><strong>To comply with any opt-out or do not disturb requests we receive from you:</strong></p>
                    <p>We understand that you may not prefer for us to contact you with any offers, promotions or details of our products and services. In the event you opt-out, we may be required to maintain information such as name, email ID/contact number and the subscription(s) that you have opted out of to ensure compliance with your requests. Also, in the future, if you wish to hear from us, you may at any time, contact us to opt-in and we would happy to keep you posted about our latest offers, promotions and/ or details of our products and services.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">How to opt-out?</h3>
                    <ul><li><strong>Email:</strong>You can click on the unsubscribe link provided in the email you receive from us.</li><li><strong>SMS:</strong>You can follow the instruction provided in the messages you receive from us</li><li><strong>Applications:</strong>You may&nbsp;<a href="https://marketing.emaarinfo.com/ehgpcp" target="_blank" rel="noreferrer noopener" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Links', 'eventAct':'Click', 'eventLbl': 'marketing.emaarinfo.com/ehgpcp', 'eventVal': 0, 'nonInteraction': 0});">CLICK HERE</a>&nbsp;option provided within the hospitality applications</li><li><strong>Contact us:</strong>You may contact us using the details provided in Section – ‘How do you contact us?’.</li></ul>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Who might we share this information to?</h3>
                    <p>We may disclose personal information that we collect, or you provide as described in this privacy policy:</p>
                    <ul><li>We may share your personal information with any member of the Emaar, including subsidiaries, affiliates and holding companies, in order to enable you to request our services, to process your payments, understand your preferences, send you information about products and services that may be of interest to you and conduct the other activities described in this privacy policy. Such group companies are located outside the European Economic Area (“EEA”). Please visit our&nbsp;<a href="https://www.emaar.com/en/international-listing" target="_blank" rel="noreferrer noopener" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Links', 'eventAct':'Click', 'eventLbl': 'emaar.com/en/international-listing', 'eventVal': 0, 'nonInteraction': 0});">WEBSITE</a>&nbsp;to see a list of locations within our corporate group.</li><li>We may use carefully selected third parties to perform services on our behalf or to assist us with the provision of services to you. For example, we may engage cloud service providers, IT service providers and other third parties to provide concierge services, housekeeping and laundry services, marketing, advertising, communications, to personalize and optimize our service, to analyze and enhance data (including data about users’ interactions with our services), and to provide legal, accounting, insurance, audit and other professional services. While providing such services, these third parties may have access to your personal information.</li><li>We may share your personal information with select business partners in sectors including travel, entertainment, lifestyle, and other industries to enable our guests to avail special offers. For example, our partnership with our airline partner enables our guests to earn miles for every stay, as well as benefit from exclusive special offers. You may find more information about our partners by visiting our website.</li><li>Where required or permitted by law, personal information may be provided to others, such as regulators and law enforcement agencies.</li><li>We may share to a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution or other sale or transfer of some or all the Company’s assets, whether as a going concern or as part of bankruptcy, liquidation or similar proceeding, in which personal information held by the Company about our Website users is among the assets transferred.</li><li>We may share with government or regulatory request to comply with any court order, law or legal process</li><li>We may share with other companies and organizations for the purposes of fraud protection and credit risk reduction if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our guests or others.</li></ul>
                    <p>The personal information that we collect from you may be transferred to, and stored at, a destination outside the EEA (for example, in Dubai). It may also be processed by staff operating outside the EEA who works for us or for one of our third-party vendors. We will take all steps that are reasonably necessary to ensure that your personal information is treated securely and in accordance with this privacy policy and applicable data protection laws, including, where relevant, entering EU standard contractual clauses (or equivalent measures) with the party outside the EEA receiving the personal information. We carry out such transfers to facilitate the performance of our contract and in pursuit of our legitimate business interests of helping us serve you better. We have implemented adequate safeguards to protect and secure the information involved in such transfers. Where we transfer personal information outside of EU, we either transfer personal information to countries that provide an adequate level of protection (as determined by the European Commission) or we have appropriate safeguards in place. Appropriate safeguards to cover these transfers are in the form of standard contractual/data protection clauses adopted by the European Commission.</p>
                    <p>If you would like more information on protection measures and transfer mechanisms, please contact us using the details provided in Section – ‘How do you contact us?’</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">How long do we keep ypur Information?</h3>
                    <p>We will only keep your personal information for as long as is reasonably necessary taking into consideration our need to answer queries or resolve problems, any other purpose outlined above or to comply with legal requirements under applicable law(s). This means that we may retain your personal information for a reasonable period, for example, the end of the contract with the guests you represent, or after your query has been addressed. In certain cases, we may retain your personal information for a longer period where extended retention periods are required by law or regulation and to establish, exercise or defend our legal rights. We will ensure that it is disposed in a secure manner when it’s no longer needed.</p>
                    <p>For more information on where and how long your personal information is stored, and for more information on your rights of erasure and portability, please contact us using the details provided in Section – ‘How do you contact us?’.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">How secure is your Information?</h3>
                    <p>Your personal data security is an important concern to us. We provide the utmost care in secure transmission of your personal information from your computer, smartphone, and other electronic devices to our servers. We use industry security standards to safeguard the confidentiality of your information (e.g. firewalls, Transport Security Layer (“TLS”) etc.) and to make sure that your personal information is secure with us.</p>
                    <p>We have implemented and maintains appropriate technical and organizational security measures, policies and procedures to protect your personal information from the accidental loss, unauthorized access, use, alteration and disclosure. All information you provide to us is stored on our secure servers behind firewalls. All payment transactions are encrypted using TLS technology. Ex: Measures we take includes:</p>
                    <ul><li>Placing confidentiality requirements on our staff and service providers;</li><li>Restriction of access to your personal information to employees and third parties strictly on a need to know basis, such as to respond to your enquiry or request;</li><li>Destroying or anonymizing personal information if it is no longer needed for the purposes for which it was collected; and</li><li>Using secure communication channels for transmitting personal data.</li></ul>
                    <p>The safety and security of your information also depend on you. Where we have given you (or where you have chosen) a password for access to certain parts of our Website, you are responsible for keeping this password confidential. We ask you not to share your password with anyone.</p>
                    <p>Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Website. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">What are your Rights?</h3>
                    <p>If you are subject to laws that provide you with such rights, you may have certain rights in relation to your personal information given below.</p>
                    <p>If you wish to access any of these rights, we may ask you for additional information to confirm your identity and for security purposes, before disclosing personal information to you. We reserve the right to charge a fee where permitted by law, for example, if your request is manifestly unfounded or excessive.</p>
                    <p>If you would like to access the below rights, you may contact us by completing a form on our&nbsp;<a href="https://dsr.emaar.com/dsr.aspx" target="_blank" rel="noreferrer noopener" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Links', 'eventAct':'Click', 'eventLbl': 'dsr.emaar.com/dsr.aspx', 'eventVal': 0, 'nonInteraction': 0});">website</a>&nbsp;or by mailing us at &nbsp;<a href="mailto:customer.privacy@emaar.ae" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Email Clicks', 'eventAct':'Click', 'eventLbl': 'customer.privacy@emaar.ae', 'eventVal': 0, 'nonInteraction': 0});">customer.privacy@emaar.ae</a>&nbsp;or sending us a communication to Data Privacy Office, PO Box 9440, Dubai, United Arab Emirates . We shall aim to comply with all requests within reasonable time in-line with applicable laws. We may not always be able to fully address your request, for example,</p>
                    <ul><li>if it would impact the confidentiality we owe to others, or</li><li>if we are legally entitled to deal with the request in a different way. or</li><li>if your request involves deletion of information that are required to comply with the legal requirements.</li></ul>
                    <p>We will make every reasonable effort to honour your request in-line with applicable laws. In the event we require additional time due to the complexity of the request, we shall promptly inform you of the same.</p>
                    <p><strong>The right to access</strong></p>
                    <p>You have the right to obtain confirmation as to whether we process personal data about you, receive a copy of your personal data held by us, and obtain certain other information about how and why we process your personal data (like the information provided in this privacy statement).</p>
                    <p><strong>The right to rectification</strong></p>
                    <p>You have the right to request for your personal data to be amended or rectified where it is inaccurate (for example, if you change your name or address) and to have incomplete personal data completed.</p>
                    <p><strong>The right to restrict processing of personal data</strong></p>
                    <p>You have the right to restrict our processing of your personal data in the following cases:</p>
                    <ul><li>Temporarily for a period when you have contested for the accuracy of the personal data;</li><li>Temporarily for a period when you have objected for the legitimate interest identified by us,</li><li>Your personal data have been unlawfully processed and you request the restriction of processing instead of deletion;</li><li>The personal data are no longer necessary in relation to the purposes for which they were collected and processed but the personal data are required by you to establish, exercise or defend legal claims;</li></ul>
                    <p>We can continue to use your personal information following a request for restriction, where:</p>
                    <ul><li>we have your consent; or</li><li>to establish, exercise or defend legal claims; or</li><li>to protect the rights of another natural or legal person.</li></ul>
                    <p><strong>The right to erasure (also known as ‘the right to be forgotten’)</strong></p>
                    <p>You have the right to obtain deletion of your personal data in the following cases:</p>
                    <ul><li>The personal data are no longer necessary in relation to the purposes for which they were collected and processed;</li><li>Our lawful basis for processing is consent, you withdraw consent and we have no other lawful basis for the processing;</li><li>Our lawful basis for processing is that the processing is necessary for a legitimate interest pursued by us, you object to our processing and we do not have overriding legitimate grounds;</li><li>You object to our processing for direct marketing purposes;</li><li>Your personal data have been unlawfully processed; and</li><li>Your personal data must be erased to comply with a legal obligation under EEA to which we are subject.</li></ul>
                    <p>We are not required to comply with your request to erase personal information if the processing of your personal information is necessary:</p>
                    <ul><li>For compliance with a legal obligation; or</li><li>For the establishment, exercise or defence of legal claims.</li></ul>
                    <p><strong>The right to object to the processing of personal data</strong></p>
                    <p>You have the right to object to our processing of your personal data in the following cases:</p>
                    <ul><li>our lawful basis for processing is that the processing is necessary for a legitimate interest pursued by us; and our processing for direct marketing purposes.</li></ul>
                    <p><strong>The right to data portability</strong></p>
                    <p>You have the right to receive your personal data provided to us and have the right to send the data to another organization (or ask us to do so if technically feasible) where our lawful basis for processing the personal data is consent or necessity for the performance of our contract with you and the processing is carried out by automated means.</p>
                    <p><strong>The right to withdraw consent at any time (where processing is based on consent)</strong></p>
                    <p>Where we process personal data based on consent, individuals have a right to withdraw consent at any time.</p>
                    <p><strong>The right to lodge a complaint with a supervisory authority</strong></p>
                    <p>If you are not content with how we manage your personal information, you can lodge a complaint with a supervisory authority in your country of residence, place of work or the country in which an alleged infringement of data protection law has occurred within the EEA. We sincerely hope that you will never need to, but if you do want to complain about our use of personal data, you can contact us in one of the ways mentioned in Section – ‘How do you contact us?’. We will look into and respond to any complaints we receive.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Updates on Policies</h3>
                    <p>This policy may change from time to time. Your continued use of our platforms after we make changes is deemed to be acceptance of those changes, so please check the policy periodically for updates.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">How do you Contact Us?</h3>
                    <p>In case of any queries related to this policy, you can contact our Data Privacy Office in one of the following ways.</p>
                    <ul><li>Email us at&nbsp;<a href="mailto:customer.privacy@emaar.ae">customer.privacy@emaar.ae</a></li><li>Call us at&nbsp;<a href="tel:80036227">800-EMAAR (36227)</a></li><li>Send us a communication to the Data Privacy Office, Emaar Hospitality Group LLC, P.O. Box 9440, Dubai, United Arab Emirates.</li></ul>
                    <div class="d-block">
                        <div class="m-2">
                            <h4>Related Links</h4>
                            <ul>
                                <li><router-link :to="{ name: 'termsconditions' }">Terms and Conditions</router-link></li>
                                <li><router-link :to="{ name: 'faqs' }">Frequently Asked Questions</router-link></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {

}
</script>

<style scoped>
    .img-header {
        background-image: url('/storage/media/connect-desk.jpg');
        background-repeat: no-repeat;
        background-size: 100% auto;
        height: 320px;
    }

    div > p:last-child {
        margin: 0;
    }

    .separator {
        border-bottom: solid 1px gray;
        height: 1px;
    }

    .separator-lightgray {
        border-bottom: solid 1px lightgray;
    }
</style>
