<template>
    <div class="d-flex flex-column">
        <div class="d-flex align-items-end p-5 img-header">
            <h1 class="mb-4 text-white">Terms & Conditions</h1>
        </div>
        <div class="d-flex justify-content-center flex-fill">
            <div class="align-self-center py-5">
                <div class="mx-auto w-75">
                    <h3 class="my-4">Introduction</h3>
                    <p>Please read these Terms &amp; Conditions carefully. These are the general Terms &amp; Conditions governing your access and use of this website (“Site”).c</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Acceptance of the terms of use</h3>
                    <p>This website is owned and operated by Emaar Properties PJSC (which term includes all subsidiaries of Emaar Properties PJSC) (“Emaar” “Company”, “we” or “us”). The following terms and conditions, the lease or sale and purchase agreement (“Property Agreement”) entered into with the Company or any of its affiliates pertaining to a commercial lease, unit or plot in an Emaar project in respect of which this website is used together with any documents they expressly incorporate by reference (collectively, these “Terms of Use”), govern your access to and use of www.vidahotels.com (the “Website”), including any content, functionality and services offered on or through the Website whether as a guest or a registered user</p>
                    <p>Please read the Terms of Use carefully before you start to use the Website. By using the Website or, where applicable, by clicking to accept or agree to the Terms of Use when this option is made available to you, you accept and agree to be bound and abide by these Terms of Use and our Privacy Policy, found at www.vidahotels.com, incorporated herein by reference. If you do not want to agree to these Terms of Use or the Privacy Policy, you must not access or use the Website.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Changes to the terms of use</h3>
                    <p>Changes to the terms of use may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Website thereafter.</p>
                    <p>Your continued use of the Website following the posting of revised Terms of Use means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Accessing the website and account security</h3>
                    <p>We reserve the right to withdraw or amend the Website, and any service or material we provide on the Website, in our sole discretion without notice. We will not be liable if for any reason all or any part of the Website is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Website, or the entire Website, to any user, including registered users.</p>
                    <p>You are responsible for:</p>
                    <ul><li>Making all arrangements necessary for you to have access to the Website.</li><li>Ensuring that all persons who access the Website through your internet connection are aware of these Terms of Use and comply with them.</li></ul>
                    <p>To access the Website or some of the resources it offers including, without limitation, payment using credit cards or other forms of electronic payment, you may be asked to provide certain registration details or other information. It is a condition of your use of the Website that all the information, including, without limitation, credit card information or information pertaining to other forms of electronic payments, you provide on the Website is correct, current and complete. You agree that all information you provide to register with this Website or otherwise, including but not limited to through the use of any interactive features on the Website, is governed by our Privacy Policy, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
                    <p>If you choose, or are provided with, a user name, password or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to this Website or portions of it using your user name, password or other security information. You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. You may only have one account with this Website. If you received more than one username, password or activation code, please notify us immediately. Your use of more than one account will represent a breach of these Terms of Use.</p>
                    <p>We have the right to disable any user name, password or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms of Use.To insure secure online payment and all other transactions of personal data, the Website uses a technology called SSL (Secure Socket Layer). SSL encrypts all communications between your computer and our server so that the information can only be read and understood by us. Usually a closed lock on your browser window shows a secure connection. For further information, please consult your browser’s security specifications. If your browser is equipped with SSL your transaction will automatically be secured. The common standard in the Internet to signal a secure site is a closed lock at the bottom of the browser. As long as the lock is displayed closed your information is secure and encrypted to avoid abuse. If you click the secure transaction link and still cannot see the closed lock, the reason may be that the window is in nested in another frame.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Intellectual property rights</h3>
                    <p>The Website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by the Company, its licensors or other providers of such material and are protected by United Arab Emirates and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.</p>
                    <p>These Terms of Use permit you to use the Website for your personal, non-commercial use only. You must not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store or transmit any of the material on our Website, except as follows:</p>
                    <ul><li>Your computer may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials.</li><li>You may store files that are automatically cached by your Web browser for display enhancement purposes.</li><li>You may print or download one copy of a reasonable number of pages of the Website for your own personal, non-commercial use and not for further reproduction, publication or distribution.</li><li>If we provide desktop, mobile or other applications for download, you may download a single copy to your computer or mobile device solely for your own personal, non-commercial use, provided you agree to be bound by our end user license agreement for such applications.</li><li>If we provide social media features with certain content, you may take such actions as are enabled by such features.</li></ul>
                    <p>You must not:</p>
                    <ul><li>Modify copies of any materials from this site.</li><li>Republish any part of the Website on another website, in any other medium (print, electronic or otherwise) or as part of any commercial service.</li><li>Use any illustrations, photographs, video or audio sequences or any graphics separately from the accompanying text.</li><li>Delete or alter any copyright, trademark or other proprietary rights notices from copies of materials from this site.</li></ul>
                    <p>No right, title or interest in or to the Website or any content on the site is transferred to you, and all rights not expressly granted are reserved by the Company. Any use of the Website not expressly permitted by these Terms of Use is a breach of these Terms of Use and may violate copyright, trademark and other laws.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Trademarks</h3>
                    <p>The Company’s names, brand names, the Company’s logos and all related names, logos, product and service names, designs and slogans are trademarks of the Company or its affiliates or licensors. You must not use such marks without the prior written permission of the Company. All other names, logos, product and service names, designs and slogans on this Website are the trademarks of their respective owners.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Prohibited Uses</h3>
                    <p>You may use the Website only for lawful purposes and in accordance with these Terms of Use. You agree not to use the Website:</p>
                    <ul><li>In any way that violates any applicable federal, local or international law or regulation, including without limitation, any form of misuse of credit cards or other forms of electronic payments.</li><li>To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter” or “spam” or any other similar solicitation.</li><li>To impersonate or attempt to impersonate the Company, a Company employee, another user or any other person or entity (including, without limitation, by using e-mail addresses or screen names associated with any of the foregoing).</li><li>To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of the Website, or which, as determined by us, may harm the Company or users of the Website or expose them to liability.</li></ul>
                    <p>Additionally, you agree not to:</p>
                    <ul><li>Use the Website in any manner that could disable, overburden, damage, or impair the Website or interfere with any other party’s use of the Website, including their ability to engage in real time activities through the Website.</li><li>Use any robot, spider or other automatic device, process or means to access the Website for any purpose, including monitoring or copying any of the material on the Website.</li><li>Use any manual process to monitor or copy any of the material on the Website or for any other unauthorized purpose without our prior written consent.</li><li>Use any device, software or routine that interferes with the proper working of the Website.</li><li>Introduce any viruses, trojan horses, worms, logic bombs or other material which is malicious or technologically harmful.</li><li>Attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Website, the server on which the Website is stored, or any server, computer or database connected to the Website.</li><li>Attack the Website via a denial-of-service attack or a distributed denial-of-service attack.</li><li>Otherwise attempt to interfere with the proper working of the Website.</li></ul>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Reliance on information posted</h3>
                    <p>The information presented on or through the Website is made available solely for general information purposes. We do not warrant the accuracy, completeness or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Website, or by anyone who may be informed of any of its contents.</p>
                    <p>Emaar reserves the absolute right, without any liability whatsoever, to amend vary or extend at any time the completion date of its projects inter alia the estimated/scheduled completion date(s) mentioned on or through the Website.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Update of the website</h3>
                    <p>We may update the content on the Website from time to time, but its content is not necessarily complete or up-to-date. Any of the material on the Website may be out of date at any given time, and we are under no obligation to update such material.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Information about you and your visits to the website</h3>
                    <p>All information we collect on this Website is subject to our Privacy Policy. By using the Website, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Online purchases and other terms and conditions</h3>
                    <p>All purchases through our site or other transactions for the sale of services formed through the Website or as a result of visits made by you are governed by these Terms of Use and the Property Agreement.</p>
                    <p>Additional terms and conditions may also apply to specific portions, services or features of the Website. All such additional terms and conditions are hereby incorporated by this reference into these Terms of Use.</p>
                    <p>Any and all payments made through this Website are subject to these Terms of Use and the Property Agreement. Consequently, the Company is under no obligation to accept any payments not made in accordance with the these Terms of Use or the Property Agreement or made following termination of any of them and you hereby acknowledge and accept that any receipt of payment through this Website or otherwise shall not be deemed or construed as an acceptance of such payment or waiver of right to reject payment at a later date.</p>
                    <p>Description of Goods and Services: The Website can be used for payment of service fees, utilities and any other charges payable by you for management of the community, compliance with community rules or required by law and in compliance with the Property Agreement.</p>
                    <p>Currency for all transactions is AED unless stated otherwise.</p>
                    <p>It is your responsibility to ensure that payment is correctly and timely received by the Company. Accordingly, we accept no liability whatsoever in this respect, and we are under no obligation to notify you of any incorrect, rejected and / or declined payments. You shall also ensure that sufficient credit is available and in the event of a “declined” credit card payment, it is your responsibility to pay any additional fees and / or charges levied by either a nominated financial institution or the Company and you shall remain responsible to pay any due amounts. Without prejudice to the foregoing, you shall notify us immediately in the event of any failed transaction or if you face or encounter any technical problems associated with the Website or its use.</p>
                    <p>If any transaction is found to be incorrect, unauthorized or fraudulent, payment may be reversed and payments shall remain due. Payment transactions will be processed on the day the transaction is submitted for payment, unless the transaction is submitted on a weekend or non-working weekday where payment will be processed the next working weekday. Upon receiving the funds into our bank account, we shall accordingly issue a proper receipt acknowledging the same. All transactions will be processed without delay, however the Company expressly disclaims any and all liability for processing delays, which may occur in any circumstance. Payment is not accepted (not deemed made) until the funds have been cleared.</p>
                    <p>Refunds of any payments (if any) made through the Website are subject to the terms and conditions of the Property Agreement. Any duplicate or excess payments received will be adjusted against future/subsequent invoices.</p>
                    <p>It is your responsibility to maintain document evidencing payment though the Website.</p>
                    <p>Any service or maintenance requests made through this Website shall be subject to the Property Agreement.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Terms of advertisements outside the united arab emirates</h3>
                    <p>All purchases shall be in Arab Emirates Dirhams (AED), regardless if the ads are in other currencies. Please note, due to currency fluctuations the amounts listed on ads in currencies other than AED may be lower or higher at the time of signing the Property Agreement. We recommend contacting our Sales Centre to confirm the purchase price in AED.</p>
                    <p>Purchases shall be subject to signing a separate Property Agreement with its own terms and conditions. The amounts due under the Property Agreement shall be listed in AED and shall be payable in AED.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Linking to the website and social media features</h3>
                    <p>You may link to any page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part.</p>
                    <p>This Website may provide certain social media features that enable you to:</p>
                    <ul><li>Link from your own or certain third-party websites to certain content on this Website.</li><li>Send e-mails or other communications with certain content, or links to certain content, on this Website.</li><li>Cause limited portions of content on this Website to be displayed or appear to be displayed on your own or certain third-party websites.</li></ul>
                    <p>You may use these features solely as they are provided by us, solely with respect to the content they are displayed with and otherwise in accordance with any additional terms and conditions we provide with respect to such features. Subject to the foregoing, you must not:</p>
                    <ul><li>Establish a link from any website that is not owned by you.</li><li>Otherwise take any action with respect to the materials on this Website that is inconsistent with any other provision of these Terms of Use.</li></ul>
                    <p>You agree to cooperate with us in causing any unauthorized framing or linking immediately to cease. We reserve the right to withdraw linking permission without notice.</p>
                    <p>We may disable all or any social media features and any links at any time without notice in our discretion.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Links from the website</h3>
                    <p>If the Website contains links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third party websites linked to this Website, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Geopraphic Restrictions</h3>
                    <p>The owner of the Website is based in the United Arab Emirates. We make no claims that the Website or any of its content is accessible or appropriate outside of the United Arab Emirates. Access to the Website may not be legal by certain persons or in certain countries. If you access the Website from outside the United Arab Emirates, you do so on your own initiative and are responsible for compliance with local laws.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Disclaimer of warranties</h3>
                    <p>You understand that we cannot and do not guarantee or warrant that the Website will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our Website for any reconstruction of any lost data.</p>
                    <p>We will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of the website or any services or items obtained through the website or to your downloading of any material posted on it, or on any website linked to it.</p>
                    <p>Your use of the website, its content and any services or items obtained through the website is at your own risk. The website, its content and any services or items obtained through the website are provided on an “as is” and “as available” basis, without any warranties of any kind, either express or implied. Neither the company nor any person associated with the company makes any warranty or representation with respect to the completeness, security, reliability, quality, accuracy or availability of the website. Without limiting the foregoing, neither the company nor anyone associated with the company represents or warrants that the website, its content or any services or items obtained through the website will be accurate, reliable, error-free or uninterrupted, that defects will be corrected, that our site or the server that makes it available are free of viruses or other harmful components or that the website or any services will otherwise meet your needs or expectations.</p>
                    <p>The company hereby disclaims all warranties of any kind, whether express or implied, statutory or otherwise, including but not limited to any warranties of non-infringement.</p>
                    <p>The foregoing does not affect any warranties which cannot be excluded or limited under applicable law.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Limitation on liability</h3>
                    <p>In no event will the company, its affiliates or their licensors, service providers, employees, agents, officers or directors be liable for damages of any kind, under any legal theory, arising out of or in connection with your use, or inability to use, the website, any websites linked to it, any content on the website or such other websites or any services or items obtained through the website or such other websites, including any direct, indirect, special, incidental, consequential or punitive damages, including but not limited to, personal injury, pain and suffering, emotional distress, loss of revenue, loss of profits, loss of business or anticipated savings, loss of use, loss of goodwill, loss of data, and whether caused by tort (including negligence), breach of contract or otherwise, even if foreseeable.</p>
                    <p>The foregoing does not affect any liability which cannot be excluded or limited under applicable law.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Idemnification</h3>
                    <p>You agree to defend, indemnify and hold harmless the Company, its affiliates, licensors and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys’ fees) arising out of or relating to your violation of these Terms of Use or your use of the Website and, any use of the Website’s content, services and products other than as expressly authorized in these Terms of Use or your use of any information obtained from the Website.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Governing law and jurisdiction</h3>
                    <p>All matters relating to the Website and these Terms of Use and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the laws in force in the Emirate of Dubai, United Arab Emirates without giving effect to any choice or conflict of law provision or rule (whether of the United Arab Emirates or any other jurisdiction).</p>
                    <p>Any legal suit, action or proceeding arising out of, or related to, these Terms of Use or the Website shall be instituted exclusively in the courts of Dubai, United Arab Emirates although we retain the right to bring any suit, action or proceeding against you for breach of these Terms of Use in your place or country of residence or any other relevant country. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Limitation on time to file claims</h3>
                    <p>Any cause of action or claim you may have arising out of or relating to these terms of use or the website must be commenced within one (1) year after the cause of action accrues, otherwise, such cause of action or claim is permanently barred.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Waiver and severability</h3>
                    <p>No waiver of by the Company of any term or condition set forth in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of the Company to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision.</p>
                    <p>If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Entire agreement</h3>
                    <p>The Terms of Use, our Privacy Policy and the Property Agreement constitute the sole and entire agreement between you and the Company with respect to the Website and supersede all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Website.</p>
                    <div class="separator separator-lightgray mb-4"></div>
                    <h3 class="my-4">Your comments and concerns</h3>
                    <p>This website is operated and owned by the Company.</p>
                    <p>In respect of requests for technical support and other communications relating to the Website, you can contact us by using our website contact form, or by emailing us at&nbsp;<a href="mailto:customerinfo@emaar.ae" onmousedown="dataLayer.push({'event': 'eventTracker', 'eventCat': 'Outbound Email Clicks', 'eventAct':'Click', 'eventLbl': 'customerinfo@emaar.ae', 'eventVal': 0, 'nonInteraction': 0});">customerinfo@emaar.ae</a>.</p>
                    <p>For feedback or suggestions, please contact us through the We Care form on the Website.</p>
                    <p>You understand and accept that by using this Website in updating, changing or altering your personal information, address(es) or contact details, you are accepting that the Company or any of its affiliates may, at their discretion, use such information as an alternative information to send legal notices under these Terms of Use or the Property Agreement. It is your obligation to immediately inform the Company of any changes to such information.</p>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {

}
</script>

<style scoped>
    .img-header {
        background-image: url('/storage/media/connect-desk.jpg');
        background-repeat: no-repeat;
        background-size: 100% auto;
        height: 320px;
    }

    div > p:last-child {
        margin: 0;
    }

    .separator {
        border-bottom: solid 1px gray;
        height: 1px;
    }

    .separator-lightgray {
        border-bottom: solid 1px lightgray;
    }
</style>
